* The Column Space Of A Matrix
  The null space (mentioned in null_space.org) has not so closely related
  cousin: The column space. This is *directly related* to the range
  of a matrix, and indeed, it actually *is* the range of a matrix.
  
** Definition Of A Column Space
   The definition of a column space is simply expressed as the span
   of all of the vectors of a matrix, programatically:

   #+BEGIN_SRC mathematica
     Col[A_] := Span[A[[1;;Length[A]]
   #+END_SRC
   
   Another way of writing this is as follows:
   #+BEGIN_SRC latex
    \begin{equation}Col A = \{\vec{b} : \vec{b} = A\vec{x} \mbox{ for some } \vec{x} \in \mathbb{R}^m\}\end{equation} 
   #+END_SRC
   
** Relation To Null Space
   We can note that like a null space, column space also has the word
   space in it. Indeed the column space of an n x m matrix A is a 
   subspace of 
   #+BEGIN_SRC latex
    \begin{equation}\mathbb{R}^n\end{equation} 
   #+END_SRC
   
   Note that that this is *different* than the space of which a null
   space is a subspace..
   
** Contrast To Null Space
   The null space and the column space in general can be thought of
   as being subspaces of different spaces: The only case in which
   this is not true is the case of a square matrix.
   
*** Simple Expression
   #+BEGIN_SRC mathematica
     DimensionNumber[Col[A]] == VecticalLength[A]
   #+END_SRC
   And
   #+BEGIN_SRC mathematica
     DimensionNumber[Nul[A]] == HorizontalLength[A]
   #+END_SRC
