* Null Space
** Relation To Subspace
   We can note that null *space* includes the word space in it: This is
   because on top of being a *subset* of some 

   #+BEGIN_SRC latex
    \begin{equation}\mathbb{R}^n\end{equation} 
   #+END_SRC
   
   It also has the following attributes where *u* and *v* exist such that:
   #+BEGIN_SRC latex
     \begin{equation}A\vec{u} = \vec{0}\end{equation}
     \begin{equation}A\vec{v} = \vec{0}\end{equation}
   #+END_SRC

      Due to these facts we know

    #+BEGIN_SRC latex
     \begin{equation}A\vec{0} = \vec{0}\end{equation}
     \begin{equation}A\vec{u + v} = A\vec{u} + V\vec{v} = \vec{0} + \vec{0} = \vec{0}\end{equation}
     \begin{equation}cA\vec{u} = c\vec{0}\end{equation}
     which in turn means
     \begin{equation}cA\vec{u} = \vec{0}\end{equation}
     which also means
     \begin{equation}Ac\vec{u} = \vec{0}\end{equation}
   #+END_SRC

   These three facts are the definition of a subspace, therefore we have shown
   why the null space is, in fact, a subspace.

* Explicit and Implicit Definitions
  An explicitly defined function can be thought of as having a defined generator that
  generators answers: This is for example, the way we can get things in a span of
  a collection of vectors, simply plug it into a generation function. On the other 
  hand, Nul A's entries are not clearly defined and require us to do computation
  to find them, far from the easy way of generating span solutions.

* Receiving Explicit Defintion Of Nul A Output
  This is a fairly simple algorithm: Here are the steps.
** Step 1
   First we must arrange our matrix to be of form:
   #+BEGIN_SRC latex
     \begin{equation}A\vec{u} = \vec{0}\end{equation}
   #+END_SRC
   
** Step 2
   Next, we must perform a row reduction algorithm upon
   the resultant matrix.
   
   #+BEGIN_SRC mathematica
     Reduce[x]
   #+END_SRC
   
** Step 3
   Once we have performed our reduce operation, we must 
   decompose our vectors using our free variables as 
   atomic weights upon the vectors, and our non-free
   variables in terms of where they appear.
   
** Step 4
   Once we perform all these operations, we can safely
   assume that all of the linear combinations of the
   decomposed units are parts of Nul A.
   
** Notes
*** Linear Independance
    Note that this resulting generator with {*u*, *v*, *w*},
    *u*, *v*, *w* will be linearly independant *UNLESS* *u*,
    *v*, and *w* are zero vectors. Aka, in this example
    *u*, *v*, and *w* all play unique roles in the vector function,
    so to say.

*** Spanning Set and Free Variables
    The amount of vectors in the resultant set will be 
    the number of free variables. This is clearly visible 
    in this example and will hold true to any number of
    free variables.

